dist: bionic
language: python
python:
  - "3.6"

# safelist
branches:
  only:
  - master

install:
  - wget https://raw.githubusercontent.com/njnmco/njnmdoc/master/njnmdoc
  - pip3 install markdown

script: python3 njnmdoc *.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  on:
    branch: master
