dist: bionic
language: python
python:
  - "3.8"

# safelist
branches:
  only:
  - master

install:
  - wget https://raw.githubusercontent.com/njnmco/njnmdoc/master/njnmdoc
  - pip3 install markdown==3.2.2 py-gfm

script:
  - python3 njnmdoc -e css=https://unpkg.com/sakura.css/css/sakura.css -r . --lazy git

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  verbose: true
  on:
    branch: master
  target_branch: master
