dist: bionic
language: python
python:
  - "3.6"

install:
  - wget https://raw.githubusercontent.com/njnmco/njnmdoc/master/njnmdoc

script: python3 njnmdoc *.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
